export const FEATURES = {
  ENABLE_ONBOARDING_TOUR: true,
  ENABLE_HOW_IT_WORKS: true,
  ENABLE_SKILL_VISUALS: true,
  ENABLE_LESSON_PLAN_WIZARD: true,
  ENABLE_ASSESSMENT_WIZARD: true,
  ENABLE_GRADE8_FULL: true,
  ENABLE_CROSS_SUBJECT_COLLAB: true,
};
