export const FEATURES = {
  ENABLE_ONBOARDING_TOUR: true,
  ENABLE_HOW_IT_WORKS: true,
  ENABLE_SKILL_VISUALS: true,
  ENABLE_LESSON_PLAN_WIZARD: true,
  ENABLE_ASSESSMENT_WIZARD: true,
  ENABLE_GRADE8_FULL: true,
  ENABLE_CROSS_SUBJECT_COLLAB: true,
  ENABLE_GRADE_RANGE_3_10: true,
  ENABLE_AI_SUBJECT: true,
  // v0.8 feature flags
  ENABLE_REALTIME_COPLANNING: true,
  ENABLE_CLASSROOM_RESOURCES_V2: true,
  ENABLE_STATE_BOARD_EXPANSION: true,
  ENABLE_INSTITUTIONAL_DASHBOARDS: true,
  ENABLE_DIKSHA_NISHTHA_PD: true,
  ENABLE_PWA_OFFLINE: true,
};
